version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: bambash/circle_ci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t $IMAGE_NAME:${CIRCLE_SHA1} .
      - run:
          name: Run tests
          command: |
            docker run --rm -ti $IMAGE_NAME:${CIRCLE_SHA1} python tests/test.py
      - run:
          name: Push image
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            docker push $IMAGE_NAME:${CIRCLE_SHA1}