version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Run tests
          command: |
            docker run --rm -ti ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} python tests/test.py
      - run:
          name: Push image
          context: DOCKER_HUB
          command: |
            docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
            docker push ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}